### ISSUE TITLE
Error building multipage site with `:http_prefix`

### ISSUE THREAD

**Issue by lhokktyn** [alphagov/tech-docs-template#183]
I'm building a multipage site that will be delivered via Gitlab pages, which requires the site be delivered from a subdirectory, e.g. `https://my-docs.test/tech-docs/`

After some reading around, `:http_prefix` seems to be the most appropriate option to enable this, but I've run into some problems when building the site with this flag enabled. It's probably user error, but have got stuck so far ...

**Set up**

```ruby
# config.rb
require 'govuk_tech_docs'
GovukTechDocs.configure(self)

configure :build do
  set :build_dir, 'public'
  activate :relative_assets
  set :http_prefix, '/tech-docs'
  page '/tech-docs/*.json', layout: false
end

set :markdown_engine, :kramdown
set :markdown,
  fenced_code_blocks: true,
  tables: true,
  no_intra_emphasis: true
```

```ruby
# tech-docs.yml
host: https://my-docs.test/tech-docs
show_govuk_logo: false
service_name: Tech Docs
service_link: /tech-docs
max_toc_heading_level: 2
multipage_nav: true
```

File layout:
```
|- source/
|-- index.html.md.erb
|-- page2.html.md.erb
|-- page3.html.md.erb
```

**Expected Outcome**

In the nav on the left, I'd expect something along the lines of:
```
<ul>
  <li>
    <a href="/tech-docs/#tech-docs">Tech Docs</a>
  </li>
  <li>
    <a href="/tech-docs/page2.html#page2">Page 2</a>
  </li>
  <li>
    <a href="/tech-docs/page3.html#page3">Page 3</a>
  </li>
</ul>
```

**Actual Outcome**

During build:
```bash
No H1 tag found. You have to at least add one H1 heading to the page: /tech-docs/favicon.ico
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:14:in `single_page_table_of_contents'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:58:in `block in render_page_tree'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:36:in `each'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:36:in `render_page_tree'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:54:in `block in render_page_tree'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:36:in `each'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:36:in `render_page_tree'
/project/vendor/ruby/2.3.0/gems/govuk_tech_docs-1.8.0/lib/govuk_tech_docs/table_of_contents/helpers.rb:28:in `multi_page_table_of_contents'
```

A similar error occurs - mentioned `search.json` rather than `favicon.ico` - if search is enabled with `enable_search: true`.

**Comment by timblair** [comment]
Thanks for reporting this, @lhokktyn. Version 1.8.1 of the [tech_docs_gem](https://rubygems.org/gems/govuk_tech_docs) has been released with a fix. Let me know if you have any issues with that version.

**Comment by lhokktyn** [comment]
Thanks for the quick turnaround on this @timblair. I've given this a go and it looks like the table of contents isn't being generated as expected when `http_prefix = /tech-guides` is set ...

I have the following files:

```
|- source/
|--index.html.md.erb
|--page2.html.md.erb
```

Within which I've code code like this

```
---
title: "Page2"
weight: 20
---

# Page2

<%= partial 'documentation/page2/sub-content' %>
```

But the TOC generated only seems to contain links to the headings present in `index.html.md.erb`:

```html
<ul>
  <li>
    <a href="/tech-guides/#technical-guides">Technical Guides</a>
    <ul>
      <li>
        <a href="/tech-guides/#subheading1">Sub Heading 1</a>
      </li>
      <li>
        <a href="/tech-guides/#subheading2">Sub heading 2</a>
      </li>
    </ul>
  </li>
</ul>
```

But I'd expect it to include the `page2` stuff too, ie.:

```html
<ul>
  <li>
    <a href="/tech-guides/#technical-guides">Technical Guides</a>
    <ul>
      <li>
        <a href="/tech-guides/#subheading1">Sub Heading 1</a>
      </li>
      <li>
        <a href="/tech-guides/#subheading2">Sub heading 2</a>
      </li>
    </ul>
  </li>
  <li>
    <a href="/tech-guides/page2.html#">Page2</a>
    <ul>
      <li>
        <a href="/tech-guides/page2.html#subcontent">Sub Content</a>
      </li>
    </ul>
  </li>
</ul>
```

It's probably user error on my part, but does this trigger any indicators as to what might be wrong?
